import {
    VEHICLE_BUS_LAYER_ID,
    VEHICLE_BUS_POINT_LAYER_ID,
    BUS_STOP_LAYER_ID,
    FERRY_STOP_LAYER_ID,
    TRAIN_STOP_LAYER_ID,
    BUS_ROUTE_LAYER_ID,
    FERRY_ROUTE_LAYER_ID,
    TRAIN_ROUTE_LAYER_ID,
} from "../baseConfig"

export const VEHICLE_LAYER_ID_BY_CONTROL = {
  Vehicle: [VEHICLE_BUS_LAYER_ID, VEHICLE_BUS_POINT_LAYER_ID],
}

export const STOP_LAYER_ID_BY_CONTROL= {
  Bus:  [BUS_STOP_LAYER_ID],
  Ferry: [FERRY_STOP_LAYER_ID],
  Train: [TRAIN_STOP_LAYER_ID]
}

export const ROUTE_LAYER_ID_BY_CONTROL = {
  Bus: [BUS_ROUTE_LAYER_ID],
  Ferry: [FERRY_ROUTE_LAYER_ID],
  Train: [TRAIN_ROUTE_LAYER_ID]
}